rules:
  indent: [1, 2]
  quotes: [1, single]
  semi: [1, never]
  comma-dangle: [1, always-multiline]
  no-unused-vars: [1, {vars: all, varsIgnorePattern: PropTypes, args: after-used, argsIgnorePattern: ^_}]
  space-before-function-paren: [1, never]
  space-after-keywords: [1, always]
  react/prop-types: 1
  react/jsx-curly-spacing: [1, never]
  react/jsx-indent-props: [1, 2]
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1
env:
  es6: true
ecmaFeatures:
  jsx: true
  modules: true
plugins: [react]
parser: babel-eslint
